# Generated by Django 6.0.3 on 2026-04-01 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0008_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionContable",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="config_contable",
                        serialize=False,
                        to="companies.company",
                    ),
                ),
                (
                    "usa_departamentos_cc",
                    models.BooleanField(
                        default=False,
                        help_text="La empresa usa departamentos y centros de costo en Saiopen",
                    ),
                ),
                (
                    "usa_proyectos_actividades",
                    models.BooleanField(
                        default=False,
                        help_text="La empresa usa proyectos y actividades en Saiopen",
                    ),
                ),
                (
                    "ultimo_conteo_gl",
                    models.BigIntegerField(
                        default=0,
                        help_text="Ultimo conteo GL sincronizado (watermark incremental)",
                    ),
                ),
                (
                    "ultima_sync_gl",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora de la ultima sincronizacion de GL exitosa",
                        null=True,
                    ),
                ),
                (
                    "ultima_sync_acct",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora de la ultima sincronizacion de ACCT exitosa",
                        null=True,
                    ),
                ),
                (
                    "sync_activo",
                    models.BooleanField(
                        default=False,
                        help_text="True si la sincronizacion esta configurada y activa",
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ultimo error de sincronizacion (vacio si OK)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion contable",
                "verbose_name_plural": "Configuraciones contables",
                "db_table": "cont_configuracion",
            },
        ),
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Codigo contable auxiliar",
                        max_digits=18,
                    ),
                ),
                ("descripcion", models.CharField(max_length=120)),
                (
                    "nivel",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Nivel jerarquico en el PUC (1=titulo, 2=grupo, etc.)",
                    ),
                ),
                (
                    "clase",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Clase de la cuenta (A=activo, P=pasivo, etc.)",
                        max_length=1,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tipo de cuenta en Saiopen",
                        max_length=3,
                    ),
                ),
                ("titulo_codigo", models.IntegerField(default=0)),
                ("grupo_codigo", models.IntegerField(default=0)),
                ("cuenta_codigo", models.IntegerField(default=0)),
                ("subcuenta_codigo", models.IntegerField(default=0)),
                (
                    "posicion_financiera",
                    models.IntegerField(
                        default=0, help_text="Posicion en el estado financiero"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_contables",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Cuentas contables",
                "db_table": "cont_cuenta_contable",
                "ordering": ["codigo"],
                "unique_together": {("company", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteo",
                    models.IntegerField(
                        help_text="PK del asiento en Firebird (GL.CONTEO)"
                    ),
                ),
                (
                    "auxiliar",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=4,
                        help_text="Codigo auxiliar contable completo",
                        max_digits=18,
                    ),
                ),
                ("auxiliar_nombre", models.CharField(max_length=120)),
                (
                    "titulo_codigo",
                    models.IntegerField(
                        blank=True,
                        help_text="PUC Nivel 1 - Titulo (1=Activo, 2=Pasivo, etc.)",
                        null=True,
                    ),
                ),
                (
                    "titulo_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "grupo_codigo",
                    models.IntegerField(
                        blank=True, help_text="PUC Nivel 2 - Grupo", null=True
                    ),
                ),
                (
                    "grupo_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "cuenta_codigo",
                    models.IntegerField(
                        blank=True, help_text="PUC Nivel 3 - Cuenta", null=True
                    ),
                ),
                (
                    "cuenta_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "subcuenta_codigo",
                    models.IntegerField(
                        blank=True, help_text="PUC Nivel 4 - Subcuenta", null=True
                    ),
                ),
                (
                    "subcuenta_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "tercero_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificacion del tercero (NIT/CC)",
                        max_length=30,
                    ),
                ),
                (
                    "tercero_nombre",
                    models.CharField(blank=True, default="", max_length=35),
                ),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("tipo", models.CharField(blank=True, default="", max_length=3)),
                ("batch", models.IntegerField(blank=True, null=True)),
                (
                    "invc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Numero de factura/documento",
                        max_length=15,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "duedate",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento (para CxC y CxP)",
                        null=True,
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        db_index=True,
                        help_text="Periodo contable YYYY-MM",
                        max_length=7,
                    ),
                ),
                (
                    "departamento_codigo",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "departamento_nombre",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "centro_costo_codigo",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "centro_costo_nombre",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "proyecto_codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                (
                    "proyecto_nombre",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "actividad_codigo",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "actividad_nombre",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_contables",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento contable",
                "verbose_name_plural": "Movimientos contables",
                "db_table": "cont_movimiento",
                "ordering": ["-fecha", "-conteo"],
                "indexes": [
                    models.Index(
                        fields=["company", "fecha"], name="idx_cont_mov_fecha"
                    ),
                    models.Index(
                        fields=["company", "periodo"], name="idx_cont_mov_periodo"
                    ),
                    models.Index(
                        fields=["company", "auxiliar"], name="idx_cont_mov_auxiliar"
                    ),
                    models.Index(
                        fields=["company", "titulo_codigo"], name="idx_cont_mov_titulo"
                    ),
                    models.Index(
                        fields=["company", "tercero_id"], name="idx_cont_mov_tercero"
                    ),
                    models.Index(
                        fields=["company", "proyecto_codigo"],
                        name="idx_cont_mov_proyecto",
                    ),
                    models.Index(
                        fields=["company", "departamento_codigo"],
                        name="idx_cont_mov_depto",
                    ),
                    models.Index(
                        fields=["company", "fecha", "titulo_codigo"],
                        name="idx_cont_mov_fecha_tit",
                    ),
                ],
                "unique_together": {("company", "conteo")},
            },
        ),
    ]
