# Generated by Django 6.0.3 on 2026-04-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_add_agent_token"),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "proyecto_codigo",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("departamento_codigo", models.IntegerField(default=0)),
                ("centro_costo_codigo", models.IntegerField(default=0)),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad Saiopen",
                "verbose_name_plural": "Actividades Saiopen",
                "db_table": "cont_actividad_saiopen",
                "ordering": ["proyecto_codigo", "codigo"],
                "unique_together": {("company", "codigo", "proyecto_codigo")},
            },
        ),
        migrations.CreateModel(
            name="ListaSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DP", "Departamento"), ("CC", "Centro de costo")],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("codigo", models.IntegerField()),
                ("descripcion", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista Saiopen (DP/CC)",
                "verbose_name_plural": "Listas Saiopen (DP/CC)",
                "db_table": "cont_lista_saiopen",
                "ordering": ["tipo", "codigo"],
                "unique_together": {("company", "tipo", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ProyectoSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "cliente_nit",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_estimada_fin", models.DateField(blank=True, null=True)),
                (
                    "costo_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("estado", models.CharField(blank=True, default="", max_length=10)),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto Saiopen",
                "verbose_name_plural": "Proyectos Saiopen",
                "db_table": "cont_proyecto_saiopen",
                "ordering": ["codigo"],
                "unique_together": {("company", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="TerceroSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_n",
                    models.CharField(
                        help_text="Identificador interno Saiopen (ID_N)", max_length=30
                    ),
                ),
                ("nit", models.CharField(blank=True, default="", max_length=30)),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
                ("direccion", models.CharField(blank=True, default="", max_length=120)),
                ("ciudad", models.CharField(blank=True, default="", max_length=60)),
                ("telefono", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.CharField(blank=True, default="", max_length=100)),
                ("es_cliente", models.BooleanField(default=False)),
                ("es_proveedor", models.BooleanField(default=False)),
                ("es_empleado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terceros_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tercero Saiopen",
                "verbose_name_plural": "Terceros Saiopen",
                "db_table": "cont_tercero_saiopen",
                "ordering": ["nombre"],
                "unique_together": {("company", "id_n")},
            },
        ),
    ]
