# Generated by Django 6.0.3 on 2026-04-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_add_agent_token"),
        ("contabilidad", "0002_add_reference_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="tercerosaiopen",
            name="acct",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cuenta contable cliente (ACCT)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="acctp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cuenta contable proveedor (ACCTP)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="creditlmt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="departamento",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="fecha_creacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="regimen",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="telefono2",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="tercerosaiopen",
            name="version_saiopen",
            field=models.BigIntegerField(
                default=0,
                help_text="Version field from CUST trigger (change detection)",
            ),
        ),
        migrations.CreateModel(
            name="ShipToSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_n",
                    models.CharField(
                        db_index=True,
                        help_text="ID_N del tercero en CUST",
                        max_length=30,
                    ),
                ),
                (
                    "succliente",
                    models.IntegerField(
                        default=0,
                        help_text="Número de sucursal. 0 = dirección principal.",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
                ("addr1", models.CharField(blank=True, default="", max_length=120)),
                ("addr2", models.CharField(blank=True, default="", max_length=120)),
                ("ciudad", models.CharField(blank=True, default="", max_length=60)),
                (
                    "departamento",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("cod_dpto", models.CharField(blank=True, default="", max_length=3)),
                (
                    "cod_municipio",
                    models.CharField(blank=True, default="", max_length=6),
                ),
                ("pais", models.CharField(blank=True, default="", max_length=60)),
                ("telefono", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.CharField(blank=True, default="", max_length=100)),
                ("zona", models.IntegerField(default=0)),
                ("id_vend", models.IntegerField(default=0)),
                ("estado", models.CharField(blank=True, default="", max_length=20)),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, help_text="True si succliente == 0"
                    ),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipto_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "ShipTo Saiopen",
                "verbose_name_plural": "ShipTos Saiopen",
                "db_table": "cont_shipto_saiopen",
                "ordering": ["id_n", "succliente"],
                "unique_together": {("company", "id_n", "succliente")},
            },
        ),
        migrations.CreateModel(
            name="TributariaSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_n",
                    models.CharField(
                        help_text="ID_N del tercero en CUST", max_length=30
                    ),
                ),
                (
                    "tdoc",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Tipo de documento (FK a TRIBUTARIA_TIPODOCUMENTO)",
                    ),
                ),
                (
                    "tipo_contribuyente",
                    models.SmallIntegerField(
                        default=0, help_text="1=persona jurídica, 2=persona natural"
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "primer_apellido",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tributaria_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tributaria Saiopen",
                "verbose_name_plural": "Tributarias Saiopen",
                "db_table": "cont_tributaria_saiopen",
                "ordering": ["id_n"],
                "unique_together": {("company", "id_n")},
            },
        ),
    ]
