# Generated by Django 6.0.3 on 2026-04-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_add_license_request"),
        ("contabilidad", "0003_add_shipto_tributaria_expand_tercero"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipdocSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clase",
                    models.CharField(
                        help_text="TIPDOC.CLASE = GL.TIPO (ej: FAC, CE)", max_length=3
                    ),
                ),
                (
                    "e",
                    models.SmallIntegerField(
                        default=0, help_text="Entidad (E en Firebird)"
                    ),
                ),
                (
                    "s",
                    models.SmallIntegerField(
                        default=0, help_text="Serie (S en Firebird)"
                    ),
                ),
                ("tipo", models.CharField(blank=True, default="", max_length=2)),
                ("consecutivo", models.IntegerField(default=0)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=35),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Abreviatura del tipo (ej: FACT, CE)",
                        max_length=10,
                    ),
                ),
                ("operar", models.CharField(blank=True, default="", max_length=2)),
                (
                    "enviafacelect",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                (
                    "prefijo_dian",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipdocs_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de documento Saiopen",
                "verbose_name_plural": "Tipos de documento Saiopen",
                "db_table": "cont_tipdoc_saiopen",
                "ordering": ["clase", "e", "s"],
                "unique_together": {("company", "clase", "e", "s")},
            },
        ),
    ]
