# Generated by Django 6.0.3 on 2026-04-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_add_license_request"),
        ("contabilidad", "0004_add_tipdoc_saiopen"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaEncabezado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("tipo", models.CharField(db_index=True, max_length=3)),
                ("id_sucursal", models.SmallIntegerField(default=1)),
                ("tercero_id", models.CharField(db_index=True, max_length=30)),
                (
                    "tercero_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("salesman", models.SmallIntegerField(blank=True, null=True)),
                (
                    "salesman_nombre",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("fecha", models.DateField(db_index=True)),
                ("duedate", models.DateField(blank=True, null=True)),
                ("periodo", models.CharField(db_index=True, max_length=7)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("posted", models.BooleanField(default=False)),
                ("closed", models.BooleanField(default=False)),
                (
                    "cod_moneda",
                    models.CharField(blank=True, default="COP", max_length=5),
                ),
                ("comentarios", models.TextField(blank=True, default="")),
                ("sincronizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_encabezado",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura encabezado",
                "verbose_name_plural": "Facturas encabezado",
                "db_table": "cont_factura_encabezado",
                "ordering": ["-fecha", "-number"],
            },
        ),
        migrations.CreateModel(
            name="FacturaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteo",
                    models.IntegerField(
                        help_text="PK del detalle en Firebird (OEDET.CONTEO)"
                    ),
                ),
                ("item_codigo", models.CharField(db_index=True, max_length=30)),
                (
                    "item_descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("location", models.CharField(blank=True, default="", max_length=3)),
                (
                    "qty_order",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_ship",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "precio_extendido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "valor_iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "porc_iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "margen_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "margen_porcentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "proyecto_codigo",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_detalle",
                        to="companies.company",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="contabilidad.facturaencabezado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura detalle",
                "verbose_name_plural": "Facturas detalle",
                "db_table": "cont_factura_detalle",
                "ordering": ["conteo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCartera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteo",
                    models.IntegerField(
                        help_text="PK del registro en Firebird (CARPRO.CONTEO)"
                    ),
                ),
                ("tercero_id", models.CharField(db_index=True, max_length=30)),
                (
                    "tercero_nombre",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "cuenta_contable",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tipo", models.CharField(blank=True, default="", max_length=3)),
                ("batch", models.IntegerField(blank=True, null=True)),
                ("invc", models.CharField(blank=True, default="", max_length=15)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("fecha", models.DateField(db_index=True)),
                ("duedate", models.DateField(blank=True, null=True)),
                ("periodo", models.CharField(db_index=True, max_length=7)),
                (
                    "debito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("departamento", models.SmallIntegerField(blank=True, null=True)),
                ("centro_costo", models.SmallIntegerField(blank=True, null=True)),
                (
                    "proyecto_codigo",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "tipo_cartera",
                    models.CharField(
                        choices=[
                            ("CXC", "Cuentas por Cobrar"),
                            ("CXP", "Cuentas por Pagar"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cartera",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de cartera",
                "verbose_name_plural": "Movimientos de cartera",
                "db_table": "cont_movimiento_cartera",
                "ordering": ["-fecha", "-conteo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteo",
                    models.IntegerField(
                        help_text="PK del registro en Firebird (ITEMACT.CONTEO)"
                    ),
                ),
                ("item_codigo", models.CharField(db_index=True, max_length=30)),
                (
                    "item_descripcion",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("location", models.CharField(db_index=True, default="", max_length=3)),
                ("tercero_id", models.CharField(blank=True, default="", max_length=30)),
                ("tipo", models.CharField(blank=True, default="", max_length=3)),
                ("batch", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateField(db_index=True)),
                ("periodo", models.CharField(db_index=True, max_length=7)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "costo_peps",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "saldo_unidades",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "saldo_pesos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("lote", models.CharField(blank=True, default="", max_length=30)),
                ("serie", models.CharField(blank=True, default="", max_length=50)),
                ("lote_vencimiento", models.DateField(blank=True, null=True)),
                ("sincronizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_inventario",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "cont_movimiento_inventario",
                "ordering": ["-fecha", "-conteo"],
            },
        ),
        migrations.AddIndex(
            model_name="facturaencabezado",
            index=models.Index(
                fields=["company", "periodo"], name="idx_fact_enc_periodo"
            ),
        ),
        migrations.AddIndex(
            model_name="facturaencabezado",
            index=models.Index(
                fields=["company", "tipo", "fecha"], name="idx_fact_enc_tipo_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="facturaencabezado",
            index=models.Index(
                fields=["company", "tercero_id"], name="idx_fact_enc_tercero"
            ),
        ),
        migrations.AddIndex(
            model_name="facturaencabezado",
            index=models.Index(
                fields=["company", "salesman"], name="idx_fact_enc_salesman"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facturaencabezado",
            unique_together={("company", "number", "tipo", "id_sucursal")},
        ),
        migrations.AddIndex(
            model_name="facturadetalle",
            index=models.Index(
                fields=["company", "item_codigo"], name="idx_fact_det_item"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facturadetalle",
            unique_together={("company", "conteo")},
        ),
        migrations.AddIndex(
            model_name="movimientocartera",
            index=models.Index(
                fields=["company", "tercero_id", "tipo_cartera"],
                name="idx_cart_tercero_tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocartera",
            index=models.Index(fields=["company", "periodo"], name="idx_cart_periodo"),
        ),
        migrations.AddIndex(
            model_name="movimientocartera",
            index=models.Index(fields=["company", "duedate"], name="idx_cart_duedate"),
        ),
        migrations.AlterUniqueTogether(
            name="movimientocartera",
            unique_together={("company", "conteo")},
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["company", "item_codigo", "fecha"], name="idx_inv_item_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["company", "location"], name="idx_inv_location"),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["company", "periodo"], name="idx_inv_periodo"),
        ),
        migrations.AlterUniqueTogether(
            name="movimientoinventario",
            unique_together={("company", "conteo")},
        ),
    ]
