# Generated by Django 6.0.3 on 2026-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0005_add_factura_cartera_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultima_sync_carpro",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la ultima sincronizacion de CARPRO exitosa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultima_sync_itemact",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la ultima sincronizacion de ITEMACT exitosa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultima_sync_oe",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la ultima sincronizacion de OE exitosa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultima_sync_oedet",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la ultima sincronizacion de OEDET exitosa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultimo_conteo_carpro",
            field=models.BigIntegerField(
                default=0,
                help_text="Ultimo conteo CARPRO sincronizado (watermark incremental)",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultimo_conteo_itemact",
            field=models.BigIntegerField(
                default=0,
                help_text="Ultimo conteo ITEMACT sincronizado (watermark incremental)",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultimo_conteo_oe",
            field=models.BigIntegerField(
                default=0,
                help_text="Ultimo conteo OE sincronizado (watermark incremental)",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncontable",
            name="ultimo_conteo_oedet",
            field=models.BigIntegerField(
                default=0,
                help_text="Ultimo conteo OEDET sincronizado (watermark incremental)",
            ),
        ),
    ]
