# Generated by Django 6.0.3 on 2026-04-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0007_fix_factura_detalle_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocontable",
            name="cruce",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de cruce (GL.CRUCE)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="movimientocontable",
            name="invc",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numero del cruce (GL.INVC)",
                max_length=15,
            ),
        ),
    ]
