# Generated by Django 6.0.3 on 2026-04-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_add_sync_server_url_to_agenttoken"),
        ("contabilidad", "0008_add_cruce_to_movimiento_contable"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendedorSaiopen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sai_key",
                    models.CharField(help_text="IDVEND como string", max_length=10),
                ),
                ("codigo", models.SmallIntegerField(help_text="VENDEDOR.IDVEND")),
                ("nombre", models.CharField(blank=True, default="", max_length=30)),
                ("telefono", models.CharField(blank=True, default="", max_length=16)),
                ("activo", models.BooleanField(default=True)),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendedores_saiopen",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendedor Saiopen",
                "verbose_name_plural": "Vendedores Saiopen",
                "db_table": "cont_vendedor_saiopen",
                "ordering": ["codigo"],
                "unique_together": {("company", "sai_key")},
            },
        ),
    ]
