# Generated by Django 6.0.3 on 2026-04-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0009_add_vendedor_saiopen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movimientoinventario",
            old_name="costo_peps",
            new_name="costo_promedio",
        ),
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="saldo_pesos",
        ),
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="saldo_unidades",
        ),
    ]
