# Generated by Django 6.0.3 on 2026-04-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0010_itemact_rename_costo_peps_remove_saldos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="item_descripcion",
        ),
    ]
