# Generated by Django 5.0.6 on 2026-03-18 05:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_alter_companymodule_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_inicio_planificada", models.DateField()),
                ("fecha_fin_planificada", models.DateField()),
                ("fecha_inicio_real", models.DateField(blank=True, null=True)),
                ("fecha_fin_real", models.DateField(blank=True, null=True)),
                (
                    "presupuesto_mano_obra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "presupuesto_materiales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "presupuesto_subcontratos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "presupuesto_equipos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "presupuesto_otros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de avance físico (0-100)",
                        max_digits=5,
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase",
                "verbose_name_plural": "Fases",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoContable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("saiopen_doc_id", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura_venta", "Factura de venta"),
                            ("factura_compra", "Factura de compra"),
                            ("orden_compra", "Orden de compra"),
                            ("recibo_caja", "Recibo de caja"),
                            ("comprobante_egreso", "Comprobante de egreso"),
                            ("nomina", "Nómina"),
                            ("anticipo", "Anticipo"),
                            ("acta_obra", "Acta de obra"),
                        ],
                        max_length=30,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=100)),
                ("fecha_documento", models.DateField()),
                ("tercero_id", models.CharField(max_length=50)),
                ("tercero_nombre", models.CharField(max_length=255)),
                ("valor_bruto", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "valor_descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("valor_neto", models.DecimalField(decimal_places=2, max_digits=15)),
                ("observaciones", models.TextField(blank=True)),
                ("sincronizado_desde_saiopen", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="proyectos.fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento contable",
                "verbose_name_plural": "Documentos contables",
                "ordering": ["-fecha_documento"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=50)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("obra_civil", "Obra civil"),
                            ("consultoria", "Consultoría"),
                            ("manufactura", "Manufactura"),
                            ("servicios", "Servicios"),
                            ("licitacion_publica", "Licitación pública"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("planificado", "Planificado"),
                            ("en_ejecucion", "En ejecución"),
                            ("suspendido", "Suspendido"),
                            ("cerrado", "Cerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("cliente_id", models.CharField(max_length=50)),
                ("cliente_nombre", models.CharField(max_length=255)),
                ("fecha_inicio_planificada", models.DateField()),
                ("fecha_fin_planificada", models.DateField()),
                ("fecha_inicio_real", models.DateField(blank=True, null=True)),
                ("fecha_fin_real", models.DateField(blank=True, null=True)),
                (
                    "presupuesto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "porcentaje_administracion",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "porcentaje_imprevistos",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "porcentaje_utilidad",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "saiopen_proyecto_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sincronizado_con_saiopen", models.BooleanField(default=False)),
                ("ultima_sincronizacion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "coordinador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proyectos_como_coordinador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_como_gerente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
                "unique_together": {("company", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Hito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "porcentaje_proyecto",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "valor_facturar",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("facturable", models.BooleanField(default=True)),
                ("facturado", models.BooleanField(default=False)),
                ("fecha_facturacion", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "documento_factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hitos_facturados",
                        to="proyectos.documentocontable",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hitos",
                        to="proyectos.fase",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hito",
                "verbose_name_plural": "Hitos",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="fase",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fases",
                to="proyectos.proyecto",
            ),
        ),
        migrations.AddField(
            model_name="documentocontable",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="proyectos.proyecto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fase",
            unique_together={("proyecto", "orden")},
        ),
        migrations.AlterUniqueTogether(
            name="documentocontable",
            unique_together={("company", "saiopen_doc_id")},
        ),
        migrations.CreateModel(
            name="TerceroProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tercero_id",
                    models.CharField(
                        help_text="NIT/ID del tercero en Saiopen", max_length=50
                    ),
                ),
                ("tercero_nombre", models.CharField(max_length=255)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("subcontratista", "Subcontratista"),
                            ("proveedor", "Proveedor"),
                            ("consultor", "Consultor"),
                            ("interventor", "Interventor"),
                            ("supervisor", "Supervisor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terceros",
                        to="proyectos.fase",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terceros",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tercero del proyecto",
                "verbose_name_plural": "Terceros del proyecto",
                "unique_together": {("proyecto", "tercero_id", "rol", "fase")},
            },
        ),
    ]
