# Generated by Django 5.0.6 on 2026-03-19 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_plan_saiopen"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=50)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "unidad_medida",
                    models.CharField(
                        help_text="m2, m3, unidad, hora, etc.", max_length=50
                    ),
                ),
                (
                    "costo_unitario_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Costo de referencia. Puede diferir por proyecto.",
                        max_digits=15,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mano_obra", "Mano de obra"),
                            ("material", "Material"),
                            ("equipo", "Equipo"),
                            ("subcontrato", "Subcontrato"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                (
                    "saiopen_actividad_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sincronizado_con_saiopen", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["codigo"],
                "unique_together": {("company", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ActividadProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad_planificada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cantidad_ejecutada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de avance de esta actividad (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="proyectos.actividad",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="proyectos.fase",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del proyecto",
                "verbose_name_plural": "Actividades del proyecto",
                "ordering": ["actividad__codigo"],
                "unique_together": {("proyecto", "actividad", "fase")},
            },
        ),
    ]
