# Generated by Django 5.0.6 on 2026-03-21 18:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0004_terceroproyecto_tercero_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TareaTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Rojo"),
                            ("orange", "Naranja"),
                            ("yellow", "Amarillo"),
                            ("green", "Verde"),
                            ("blue", "Azul"),
                            ("purple", "Morado"),
                            ("pink", "Rosa"),
                            ("gray", "Gris"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de Tarea",
                "verbose_name_plural": "Etiquetas de Tareas",
                "ordering": ["nombre"],
                "unique_together": {("company", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[
                            (1, "Baja"),
                            (2, "Normal"),
                            (3, "Alta"),
                            (4, "Urgente"),
                        ],
                        default=2,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_hacer", "Por Hacer"),
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("bloqueada", "Bloqueada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="por_hacer",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_completado",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "horas_estimadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "horas_registradas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("es_recurrente", models.BooleanField(default=False)),
                (
                    "frecuencia_recurrencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("proxima_generacion", models.DateField(blank=True, null=True)),
                (
                    "actividad_proyecto_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        help_text="ID de ActividadProyecto original (solo para migración)",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas",
                        to="proyectos.fase",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tareas_siguiendo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtareas",
                        to="proyectos.tarea",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tareas", to="proyectos.tareatag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-prioridad", "fecha_limite", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["proyecto", "estado"],
                        name="proyectos_t_proyect_274ed3_idx",
                    ),
                    models.Index(
                        fields=["responsable"], name="proyectos_t_respons_aedd8d_idx"
                    ),
                    models.Index(
                        fields=["fecha_limite"], name="proyectos_t_fecha_l_e571a8_idx"
                    ),
                ],
            },
        ),
    ]
