# Generated by Django 5.0.6 on 2026-03-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0005_agregar_tareas"),
        ("terceros", "0002_alter_tercero_tipo_tercero"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Tercero (cliente) asociado a esta tarea (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tareas",
                to="terceros.tercero",
                verbose_name="Cliente",
            ),
        ),
    ]
