# Generated by Django 5.0.6 on 2026-03-23 04:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0006_add_cliente_to_tarea"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionmodulo",
            name="modo_timesheet",
            field=models.CharField(
                choices=[
                    ("manual", "Manual — registro de horas"),
                    ("cronometro", "Cronómetro — tiempo real"),
                    ("ambos", "Ambos modos disponibles"),
                    ("desactivado", "Desactivado"),
                ],
                default="ambos",
                max_length=20,
                verbose_name="Modo de timesheet",
            ),
        ),
        migrations.CreateModel(
            name="SesionTrabajo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inicio", models.DateTimeField(verbose_name="Inicio")),
                (
                    "fin",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                ("pausas", models.JSONField(default=list, verbose_name="Pausas")),
                (
                    "duracion_segundos",
                    models.IntegerField(default=0, verbose_name="Duración (segundos)"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("pausada", "Pausada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_trabajo",
                        to="proyectos.tarea",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_trabajo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Trabajo",
                "verbose_name_plural": "Sesiones de Trabajo",
                "db_table": "sesiones_trabajo",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["tarea", "usuario"],
                        name="sesiones_tr_tarea_i_bf52b6_idx",
                    ),
                    models.Index(
                        fields=["estado", "usuario"],
                        name="sesiones_tr_estado_11ed53_idx",
                    ),
                ],
            },
        ),
    ]
