# Generated by Django 5.0.6 on 2026-03-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0008_actividad_saiopen_fase_estado_tarea_campos"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tarea",
            new_name="proyectos_t_fase_id_3050a6_idx",
            old_name="proyectos_t_fase_es_idx",
        ),
        migrations.AlterField(
            model_name="actividadsaiopen",
            name="costo_unitario_base",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Costo de referencia. Puede diferir por tarea.",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="fase",
            name="porcentaje_avance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de avance físico (0-100). Calculado automáticamente desde tareas.",
                max_digits=5,
            ),
        ),
    ]
