# Generated by Django 5.0.6 on 2026-03-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proyectos",
            "0009_rename_proyectos_t_fase_es_idx_proyectos_t_fase_id_3050a6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarea",
            name="actividad_proyecto_id",
        ),
        migrations.AddField(
            model_name="tarea",
            name="actividad_proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Actividad del proyecto a la que pertenece esta tarea.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tareas",
                to="proyectos.actividadproyecto",
            ),
        ),
    ]
