# Generated by Django 5.0.6 on 2026-03-24 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0010_remove_tarea_actividad_proyecto_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TareaDependencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_dependencia",
                    models.CharField(
                        choices=[
                            ("FS", "Finish to Start (FS)"),
                            ("SS", "Start to Start (SS)"),
                            ("FF", "Finish to Finish (FF)"),
                        ],
                        default="FS",
                        max_length=2,
                    ),
                ),
                (
                    "retraso_dias",
                    models.IntegerField(
                        default=0,
                        help_text="Lag time en días (puede ser negativo para adelantar).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tarea_predecesora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucesoras",
                        to="proyectos.tarea",
                        verbose_name="Tarea predecesora",
                    ),
                ),
                (
                    "tarea_sucesora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecesoras",
                        to="proyectos.tarea",
                        verbose_name="Tarea sucesora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependencia de tarea",
                "verbose_name_plural": "Dependencias de tareas",
                "unique_together": {("company", "tarea_predecesora", "tarea_sucesora")},
            },
        ),
    ]
