# Generated by Django 5.0.6 on 2026-03-26 21:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0011_tarea_dependencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "validado",
                    models.BooleanField(default=False, verbose_name="Validado"),
                ),
                (
                    "fecha_validacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de validación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="proyectos.tarea",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheets_validados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Horas",
                "verbose_name_plural": "Registros de Horas",
                "db_table": "timesheet_entries",
                "ordering": ["-fecha", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "fecha"],
                        name="timesheet_e_usuario_2211d2_idx",
                    ),
                    models.Index(
                        fields=["tarea", "validado"],
                        name="timesheet_e_tarea_i_788781_idx",
                    ),
                ],
                "unique_together": {("tarea", "usuario", "fecha")},
            },
        ),
    ]
