# Generated by Django 5.0.6 on 2026-03-27 03:38

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def crear_capacidad_default(apps, schema_editor):
    """
    Crea ResourceCapacity de 40h/semana indefinida para todos los usuarios
    activos de cada empresa que aún no tengan capacidad registrada.
    """
    ResourceCapacity = apps.get_model('proyectos', 'ResourceCapacity')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    for usuario in User.objects.filter(is_active=True).exclude(company_id=None):
        ResourceCapacity.objects.get_or_create(
            company_id=usuario.company_id,
            usuario_id=usuario.id,
            fecha_inicio=datetime.date(2020, 1, 1),
            defaults={
                'horas_por_semana': Decimal('40.00'),
                'fecha_fin': None,
                'activo': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        (
            "proyectos",
            "0014_rename_proyectos_t_fase_id_3050a6_idx_proyectos_t_fase_id_11ba2a_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacaciones"),
                            ("sick_leave", "Incapacidad"),
                            ("holiday", "Festivo"),
                            ("training", "Capacitación"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de ausencia",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Aprobado"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_absences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_availabilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad de recurso",
                "verbose_name_plural": "Disponibilidades de recursos",
                "ordering": ["fecha_inicio", "usuario"],
            },
        ),
        migrations.CreateModel(
            name="ResourceCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horas_por_semana",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas laborables por semana (máx. 168 = 7 días × 24h).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("168.00")),
                        ],
                        verbose_name="Horas por semana",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Dejar en blanco para capacidad indefinida.",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_capacities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidad de recurso",
                "verbose_name_plural": "Capacidades de recursos",
                "ordering": ["usuario", "fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "porcentaje_asignacion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fracción de la capacidad semanal del usuario dedicada a esta tarea (0.01–100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje de asignación",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="proyectos.task",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de recurso",
                "verbose_name_plural": "Asignaciones de recursos",
                "ordering": ["fecha_inicio", "usuario"],
                "indexes": [
                    models.Index(
                        fields=["company", "usuario", "fecha_inicio", "fecha_fin"],
                        name="idx_rassign_co_us_dates",
                    ),
                    models.Index(
                        fields=["tarea", "fecha_inicio", "fecha_fin"],
                        name="idx_rassign_tarea_dates",
                    ),
                    models.Index(
                        fields=["usuario", "activo"], name="idx_rassign_us_activo"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resourceassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="ck_rassign_fecha_fin_gte_inicio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourceassignment",
            unique_together={("company", "tarea", "usuario")},
        ),
        migrations.AddIndex(
            model_name="resourceavailability",
            index=models.Index(
                fields=["company", "usuario", "aprobado", "fecha_inicio", "fecha_fin"],
                name="idx_ravail_co_us_ap_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceavailability",
            index=models.Index(
                fields=["company", "aprobado"], name="idx_ravail_co_aprobado"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="ck_ravail_fecha_fin_gte_inicio",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecapacity",
            index=models.Index(
                fields=["company", "usuario", "activo", "fecha_inicio"],
                name="idx_rcap_co_us_active_start",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecapacity",
            index=models.Index(
                condition=models.Q(("fecha_fin__isnull", True)),
                fields=["company", "usuario"],
                name="idx_rcap_open_ended",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcecapacity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_fin__isnull", True),
                    ("fecha_fin__gt", models.F("fecha_inicio")),
                    _connector="OR",
                ),
                name="ck_rcap_fecha_fin_gt_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcecapacity",
            constraint=models.CheckConstraint(
                condition=models.Q(("horas_por_semana__gt", 0)),
                name="ck_rcap_horas_positivas",
            ),
        ),
        migrations.RunPython(
            code=crear_capacidad_default,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
