# Generated by Django 5.0.6 on 2026-03-27 21:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0015_resource_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBaseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_active_baseline",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Solo un baseline activo por proyecto.",
                        verbose_name="Baseline activo",
                    ),
                ),
                (
                    "tasks_snapshot",
                    models.JSONField(default=list, verbose_name="Snapshot de tareas"),
                ),
                (
                    "resources_snapshot",
                    models.JSONField(default=list, verbose_name="Snapshot de recursos"),
                ),
                (
                    "project_end_date_snapshot",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha fin proyecto (snapshot)",
                    ),
                ),
                (
                    "total_tasks_snapshot",
                    models.IntegerField(
                        default=0, verbose_name="Total tareas (snapshot)"
                    ),
                ),
                (
                    "critical_path_snapshot",
                    models.JSONField(
                        default=list,
                        help_text="Lista de task_ids que formaban la ruta crítica.",
                        verbose_name="Ruta crítica (snapshot)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="proyectos.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline de proyecto",
                "verbose_name_plural": "Baselines de proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskConstraint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("asap", "As Soon As Possible"),
                            ("alap", "As Late As Possible"),
                            ("must_start_on", "Must Start On"),
                            ("must_finish_on", "Must Finish On"),
                            ("start_no_earlier_than", "Start No Earlier Than"),
                            ("start_no_later_than", "Start No Later Than"),
                            ("finish_no_earlier_than", "Finish No Earlier Than"),
                            ("finish_no_later_than", "Finish No Later Than"),
                        ],
                        default="asap",
                        max_length=30,
                        verbose_name="Tipo de restricción",
                    ),
                ),
                (
                    "constraint_date",
                    models.DateField(
                        blank=True,
                        help_text="Requerido para tipos con fecha (must_start_on, start_no_earlier_than, etc.).",
                        null=True,
                        verbose_name="Fecha de restricción",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_constraints",
                        to="proyectos.task",
                        verbose_name="Tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restricción de tarea",
                "verbose_name_plural": "Restricciones de tareas",
            },
        ),
        migrations.CreateModel(
            name="WhatIfScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "task_changes",
                    models.JSONField(default=dict, verbose_name="Cambios en tareas"),
                ),
                (
                    "resource_changes",
                    models.JSONField(default=dict, verbose_name="Cambios en recursos"),
                ),
                (
                    "dependency_changes",
                    models.JSONField(
                        default=dict, verbose_name="Cambios en dependencias"
                    ),
                ),
                (
                    "simulated_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin simulada"
                    ),
                ),
                (
                    "simulated_critical_path",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de task_ids en la ruta crítica del escenario.",
                        null=True,
                        verbose_name="Ruta crítica simulada",
                    ),
                ),
                (
                    "days_delta",
                    models.IntegerField(
                        blank=True,
                        help_text="Días de diferencia vs plan actual. Positivo = retraso, negativo = adelanto.",
                        null=True,
                        verbose_name="Delta días",
                    ),
                ),
                (
                    "tasks_affected_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tareas afectadas"
                    ),
                ),
                (
                    "simulation_ran_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Simulación ejecutada en"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_what_if_scenarios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="what_if_scenarios",
                        to="proyectos.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escenario What-If",
                "verbose_name_plural": "Escenarios What-If",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectbaseline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active_baseline", True)),
                fields=("company", "project"),
                name="uq_one_active_baseline_per_project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskconstraint",
            unique_together={("company", "task", "constraint_type")},
        ),
    ]
