# Generated by Django 5.0.6 on 2026-03-27 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0016_feature_6_scheduling_models"),
        ("terceros", "0002_alter_tercero_tipo_tercero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["proyecto", "fecha_inicio", "fecha_fin"],
                name="idx_task_proj_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["fecha_fin"], name="idx_task_fecha_fin"),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["tarea_predecesora"], name="idx_tdep_predecessor"
            ),
        ),
    ]
