# Generated by Django 6.0.3 on 2026-03-28 00:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("proyectos", "0017_feature_6_scheduling_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(verbose_name="Fecha del snapshot")),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Costo mano de obra real",
                    ),
                ),
                (
                    "expense_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Costo gastos reales",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Costo total real",
                    ),
                ),
                (
                    "planned_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Copia del planned_total_budget o approved_budget vigente al tomar el snapshot.",
                        max_digits=15,
                        verbose_name="Presupuesto planificado (en fecha)",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Positivo = bajo presupuesto. Negativo = sobre presupuesto.",
                        max_digits=15,
                        verbose_name="Variación (planned - actual)",
                    ),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="Variación (%)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_snapshots",
                        to="proyectos.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Presupuesto",
                "verbose_name_plural": "Snapshots de Presupuesto",
                "db_table": "budget_snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "snapshot_date"],
                        name="budget_snap_company_f30e44_idx",
                    ),
                    models.Index(
                        fields=["project", "snapshot_date"],
                        name="budget_snap_project_f3b0e8_idx",
                    ),
                ],
                "unique_together": {("project", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planned_labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Costo mano de obra planificado",
                    ),
                ),
                (
                    "planned_expense_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Costo gastos planificado",
                    ),
                ),
                (
                    "planned_total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puede incluir AIU y contingencia además de labor + expense. No se auto-calcula: el gestor lo define explícitamente.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Presupuesto total planificado",
                    ),
                ),
                (
                    "approved_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Presupuesto aprobado",
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "alert_threshold_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="Porcentaje de ejecución del presupuesto que activa una alerta.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Umbral de alerta (%)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda (ISO 4217)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="proyectos.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto de Proyecto",
                "verbose_name_plural": "Presupuestos de Proyectos",
                "db_table": "project_budgets",
                "indexes": [
                    models.Index(
                        fields=["company", "approved_date"],
                        name="project_bud_company_c2c626_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("planned_labor_cost__gte", Decimal("0.00"))
                        ),
                        name="project_budget_labor_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("planned_expense_cost__gte", Decimal("0.00"))
                        ),
                        name="project_budget_expense_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("planned_total_budget__gte", Decimal("0.00"))
                        ),
                        name="project_budget_total_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materials", "Materiales"),
                            ("equipment", "Equipos"),
                            ("travel", "Viáticos y transporte"),
                            ("subcontractor", "Subcontratista"),
                            ("software", "Software / licencias"),
                            ("training", "Capacitación"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda (ISO 4217)"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Fecha del gasto")),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del recibo en S3 o servicio de almacenamiento.",
                        verbose_name="URL comprobante",
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(default=True, verbose_name="Facturable"),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_paid",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pagado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="proyectos.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto de Proyecto",
                "verbose_name_plural": "Gastos de Proyecto",
                "db_table": "project_expenses",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "expense_date"],
                        name="project_exp_project_a38cfe_idx",
                    ),
                    models.Index(
                        fields=["project", "billable"],
                        name="project_exp_project_c198c9_idx",
                    ),
                    models.Index(
                        fields=["company", "category"],
                        name="project_exp_company_8c4aa0_idx",
                    ),
                    models.Index(
                        fields=["company", "expense_date"],
                        name="project_exp_company_a08ba2_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="project_expense_amount_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceCostRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(verbose_name="Fecha inicio vigencia")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="NULL indica que la tarifa está actualmente vigente.",
                        null=True,
                        verbose_name="Fecha fin vigencia",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tarifa por hora",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda (ISO 4217)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_rates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Costo de Recurso",
                "verbose_name_plural": "Tarifas de Costo de Recursos",
                "db_table": "resource_cost_rates",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "company", "start_date"],
                        name="resource_co_user_id_55850d_idx",
                    ),
                    models.Index(
                        fields=["company", "start_date", "end_date"],
                        name="resource_co_company_b7caac_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_date__lte", models.F("end_date")),
                            ("end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="resource_cost_rate_start_before_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("hourly_rate__gte", Decimal("0.00"))),
                        name="resource_cost_rate_non_negative",
                    ),
                ],
            },
        ),
    ]
