# Generated by Django 5.0.6 on 2026-03-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0019_feature_7_budget_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("labor", "Mano de obra"),
                    ("material", "Material"),
                    ("equipment", "Equipo"),
                    ("subcontract", "Subcontrato"),
                    ("milestone", "Hito"),
                ],
                max_length=20,
            ),
        ),
    ]
