# Generated by Django 6.0.3 on 2026-03-31 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_rename_ventas_cobros_to_crm_soporte"),
        ("proyectos", "0021_fase_orden_deferrable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("construccion", "Construcción"),
                            ("software", "Desarrollo de Software"),
                            ("evento", "Evento"),
                            ("marketing", "Marketing"),
                            ("product_launch", "Lanzamiento de Producto"),
                        ],
                        max_length=30,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        default="folder",
                        help_text="Nombre del Material Icon para representar la plantilla.",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "duracion_estimada",
                    models.IntegerField(
                        default=30,
                        help_text="Duración total estimada del proyecto en días calendario.",
                        verbose_name="Duración estimada (días)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activa"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Proyecto",
                "verbose_name_plural": "Plantillas de Proyecto",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="PlantillaFase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "porcentaje_duracion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Qué porcentaje de la duración total ocupa esta fase (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje de duración",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "plantilla_proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases_plantilla",
                        to="proyectos.plantillaproyecto",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase de Plantilla",
                "verbose_name_plural": "Fases de Plantilla",
                "ordering": ["orden"],
                "unique_together": {("plantilla_proyecto", "orden")},
            },
        ),
        migrations.CreateModel(
            name="PlantillaTarea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "duracion_dias",
                    models.IntegerField(
                        default=1,
                        help_text="Duración estimada de la tarea en días calendario.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duración (días)",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[
                            (1, "Baja"),
                            (2, "Normal"),
                            (3, "Alta"),
                            (4, "Urgente"),
                        ],
                        default=2,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "actividad_saiopen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantilla_tareas",
                        to="proyectos.saiopenactivity",
                        verbose_name="Actividad Saiopen",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "plantilla_fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas_plantilla",
                        to="proyectos.plantillafase",
                        verbose_name="Fase de plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Plantilla",
                "verbose_name_plural": "Tareas de Plantilla",
                "ordering": ["orden"],
                "unique_together": {("plantilla_fase", "orden")},
            },
        ),
        migrations.CreateModel(
            name="PlantillaDependencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_dependencia",
                    models.CharField(
                        choices=[
                            ("FS", "Finish to Start (FS)"),
                            ("SS", "Start to Start (SS)"),
                            ("FF", "Finish to Finish (FF)"),
                        ],
                        default="FS",
                        max_length=2,
                        verbose_name="Tipo de dependencia",
                    ),
                ),
                (
                    "lag_time",
                    models.IntegerField(
                        default=0,
                        help_text="Días de desfase. Puede ser negativo para adelantar.",
                        verbose_name="Lag time (días)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tarea_predecesora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucesoras_plantilla",
                        to="proyectos.plantillatarea",
                        verbose_name="Tarea predecesora",
                    ),
                ),
                (
                    "tarea_sucesora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecesoras_plantilla",
                        to="proyectos.plantillatarea",
                        verbose_name="Tarea sucesora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependencia de Plantilla",
                "verbose_name_plural": "Dependencias de Plantilla",
                "unique_together": {("tarea_predecesora", "tarea_sucesora")},
            },
        ),
    ]
