# Generated by Django 6.0.3 on 2026-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0022_add_plantilla_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantillaproyecto",
            options={
                "ordering": ["tipo", "nombre"],
                "verbose_name": "Plantilla de Proyecto",
                "verbose_name_plural": "Plantillas de Proyecto",
            },
        ),
        migrations.RemoveField(
            model_name="plantillaproyecto",
            name="categoria",
        ),
        migrations.AddField(
            model_name="plantillaproyecto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("civil_works", "Obra civil"),
                    ("consulting", "Consultoría"),
                    ("manufacturing", "Manufactura"),
                    ("services", "Servicios"),
                    ("public_tender", "Licitación pública"),
                    ("other", "Otro"),
                ],
                default="other",
                help_text="Tipo de proyecto que genera esta plantilla. Determina el consecutivo de código.",
                max_length=30,
                verbose_name="Tipo de proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cliente_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="cliente_nombre",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
