# Generated by Django 6.0.3 on 2026-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_add_license_request"),
        ("proyectos", "0024_plantillatarea_actividad_to_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingdocument",
            name="batch_gl",
            field=models.IntegerField(
                blank=True,
                help_text="MovimientoContable.batch — número secuencial del documento en Saiopen",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountingdocument",
            name="invc_gl",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MovimientoContable.invc — referencia externa impresa en el documento",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="accountingdocument",
            name="tipdoc_descripcion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="TIPDOC.DESCRIPCION — nombre legible del tipo de documento",
                max_length=35,
            ),
        ),
        migrations.AddField(
            model_name="accountingdocument",
            name="tipdoc_sigla",
            field=models.CharField(
                blank=True,
                default="",
                help_text="TIPDOC.SIGLA — abreviatura para badge en UI",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="accountingdocument",
            name="tipo_gl",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MovimientoContable.tipo — corresponde a TIPDOC.CLASE",
                max_length=3,
            ),
        ),
        migrations.AddIndex(
            model_name="accountingdocument",
            index=models.Index(
                fields=["company", "tipo_gl", "batch_gl"], name="idx_proj_doc_gl_key"
            ),
        ),
    ]
