# Generated by Django 5.0.6 on 2026-03-23 18:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                ("texto", models.TextField()),
                ("editado", models.BooleanField(default=False)),
                ("editado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "menciones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comentarios_mencionado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="notifications.comentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "db_table": "comentarios",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="coment_ct_oid_created_idx",
                    ),
                    models.Index(fields=["padre"], name="coment_padre_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comentario", "Nuevo Comentario"),
                            ("mencion", "Mención"),
                            ("aprobacion", "Aprobación Requerida"),
                            ("aprobacion_resultado", "Resultado de Aprobación"),
                            ("asignacion", "Nueva Asignación"),
                            ("cambio_estado", "Cambio de Estado"),
                            ("vencimiento", "Vencimiento Próximo"),
                            ("sistema", "Mensaje del Sistema"),
                            ("chat", "Mensaje Directo"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("object_id", models.UUIDField()),
                ("url_accion", models.CharField(blank=True, max_length=500)),
                (
                    "ancla",
                    models.CharField(
                        blank=True,
                        help_text="Ancla HTML para scroll directo. Ej: #comentario-<uuid>",
                        max_length=100,
                    ),
                ),
                ("leida", models.BooleanField(db_index=True, default=False)),
                ("leida_en", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "leida", "-created_at"],
                        name="notif_usr_leida_created_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"], name="notif_ct_oid_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaNotificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comentario", "Nuevo Comentario"),
                            ("mencion", "Mención"),
                            ("aprobacion", "Aprobación Requerida"),
                            ("aprobacion_resultado", "Resultado de Aprobación"),
                            ("asignacion", "Nueva Asignación"),
                            ("cambio_estado", "Cambio de Estado"),
                            ("vencimiento", "Vencimiento Próximo"),
                            ("sistema", "Mensaje del Sistema"),
                            ("chat", "Mensaje Directo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("habilitado_app", models.BooleanField(default=True)),
                ("habilitado_email", models.BooleanField(default=True)),
                ("habilitado_push", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_notificacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Notificación",
                "verbose_name_plural": "Preferencias de Notificación",
                "db_table": "preferencias_notificacion",
                "unique_together": {("company", "usuario", "tipo")},
            },
        ),
    ]
