# Generated by Django 5.0.6 on 2026-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="recordatorio_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en que el recordatorio debe re-aparecer. NULL = aparece inmediatamente.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="snoozed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Si es futuro, la notificación no aparece en la lista hasta esta fecha.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preferencianotificacion",
            name="agrupar",
            field=models.BooleanField(default=True, verbose_name="Agrupar similares"),
        ),
        migrations.AddField(
            model_name="preferencianotificacion",
            name="frecuencia",
            field=models.CharField(
                choices=[
                    ("inmediata", "Inmediata"),
                    ("cada_hora", "Resumen cada hora"),
                    ("diaria", "Resumen diario (9 AM)"),
                ],
                default="inmediata",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="preferencianotificacion",
            name="sonido_habilitado",
            field=models.BooleanField(default=True, verbose_name="Sonido habilitado"),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("comentario", "Nuevo Comentario"),
                    ("mencion", "Mención"),
                    ("aprobacion", "Aprobación Requerida"),
                    ("aprobacion_resultado", "Resultado de Aprobación"),
                    ("asignacion", "Nueva Asignación"),
                    ("cambio_estado", "Cambio de Estado"),
                    ("vencimiento", "Vencimiento Próximo"),
                    ("sistema", "Mensaje del Sistema"),
                    ("chat", "Mensaje Directo"),
                    ("recordatorio", "Recordatorio"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="preferencianotificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("comentario", "Nuevo Comentario"),
                    ("mencion", "Mención"),
                    ("aprobacion", "Aprobación Requerida"),
                    ("aprobacion_resultado", "Resultado de Aprobación"),
                    ("asignacion", "Nueva Asignación"),
                    ("cambio_estado", "Cambio de Estado"),
                    ("vencimiento", "Vencimiento Próximo"),
                    ("sistema", "Mensaje del Sistema"),
                    ("chat", "Mensaje Directo"),
                    ("recordatorio", "Recordatorio"),
                ],
                max_length=30,
            ),
        ),
    ]
