# Generated by Django 6.0.3 on 2026-04-01 21:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0008_company_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "es_privado",
                    models.BooleanField(
                        default=True,
                        help_text="Solo visible para el creador y usuarios con share",
                    ),
                ),
                ("es_favorito", models.BooleanField(default=False)),
                (
                    "es_default",
                    models.BooleanField(
                        default=False,
                        help_text="Dashboard por defecto del usuario. Solo uno por usuario.",
                    ),
                ),
                (
                    "orientacion",
                    models.CharField(
                        choices=[("portrait", "Vertical"), ("landscape", "Horizontal")],
                        default="portrait",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["-es_default", "-es_favorito", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type_code",
                    models.CharField(
                        help_text="Codigo del tipo de tarjeta del catalogo (ej: BALANCE_GENERAL)",
                        max_length=50,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Barras"),
                            ("pie", "Torta"),
                            ("line", "Linea"),
                            ("kpi", "KPI"),
                            ("table", "Tabla"),
                            ("area", "Area"),
                            ("waterfall", "Cascada"),
                            ("gauge", "Indicador"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                ("pos_x", models.SmallIntegerField(default=0)),
                ("pos_y", models.SmallIntegerField(default=0)),
                ("width", models.SmallIntegerField(default=2)),
                ("height", models.SmallIntegerField(default=2)),
                (
                    "filtros_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros especificos de esta tarjeta (periodos, terceros, etc.)",
                    ),
                ),
                (
                    "titulo_personalizado",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Si esta vacio, se usa el titulo del catalogo",
                        max_length=100,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta de dashboard",
                "verbose_name_plural": "Tarjetas de dashboard",
                "ordering": ["orden", "pos_y", "pos_x"],
            },
        ),
        migrations.CreateModel(
            name="DashboardShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puede_editar", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "compartido_con",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards_compartidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compartido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards_compartidos_por_mi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard compartido",
                "verbose_name_plural": "Dashboards compartidos",
                "unique_together": {("dashboard", "compartido_con")},
            },
        ),
        migrations.CreateModel(
            name="ModuleTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        help_text="Codigo del modulo (ej: dashboard)", max_length=50
                    ),
                ),
                ("iniciado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField(help_text="iniciado_en + 14 dias")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_trials",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trial de modulo",
                "verbose_name_plural": "Trials de modulo",
                "unique_together": {("company", "module_code")},
            },
        ),
    ]
