# Generated by Django 6.0.3 on 2026-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="filtros_default",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Filtros predeterminados del dashboard. Se cargan automaticamente al abrir el dashboard en el viewer. Estructura: {fecha_desde, fecha_hasta, periodo, tercero_ids, proyecto_codigos, departamento_codigos, centro_costo_codigos, agrupar_por_mes, anio}",
            ),
        ),
    ]
