# Generated by Django 6.0.3 on 2026-04-11 04:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_add_license_request"),
        ("dashboard", "0002_add_filtros_default_to_dashboard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("es_privado", models.BooleanField(default=True)),
                ("es_favorito", models.BooleanField(default=False)),
                (
                    "es_template",
                    models.BooleanField(
                        default=False,
                        help_text="True para reportes predefinidos (templates)",
                    ),
                ),
                (
                    "fuentes",
                    models.JSONField(
                        default=list,
                        help_text='Lista de fuentes: ["gl", "facturacion", "cartera", "inventario"]',
                    ),
                ),
                (
                    "campos_config",
                    models.JSONField(
                        default=list,
                        help_text='Campos configurados. Ejemplo: [{"source": "gl", "field": "tercero_nombre", "role": "dimension", "label": "Tercero"}]',
                    ),
                ),
                (
                    "tipo_visualizacion",
                    models.CharField(
                        choices=[
                            ("table", "Tabla"),
                            ("pivot", "Tabla Dinámica"),
                            ("bar", "Barras"),
                            ("line", "Líneas"),
                            ("pie", "Torta"),
                            ("area", "Área"),
                            ("kpi", "KPI"),
                            ("waterfall", "Cascada"),
                        ],
                        default="table",
                        max_length=20,
                    ),
                ),
                (
                    "viz_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Config de pivot, chart, kpi según tipo_visualizacion",
                    ),
                ),
                ("filtros", models.JSONField(blank=True, default=dict)),
                ("orden_config", models.JSONField(blank=True, default=list)),
                ("limite_registros", models.IntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "template_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_derivados",
                        to="dashboard.reportbi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_bi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte BI",
                "verbose_name_plural": "Reportes BI",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportBIShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puede_editar", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "compartido_con",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_bi_compartidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compartido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_bi_compartidos_por_mi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="dashboard.reportbi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte BI compartido",
                "verbose_name_plural": "Reportes BI compartidos",
                "unique_together": {("reporte", "compartido_con")},
            },
        ),
    ]
