# Generated by Django 6.0.3 on 2026-04-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_dashboardcard_bi_report_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportbi",
            name="descripcion",
        ),
    ]
