# Generated by Django 6.0.3 on 2026-03-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_license_concurrent_modules_history"),
        ("users", "0003_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant_activo",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant activo seleccionado por usuario soporte",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="soporte_activos",
                to="companies.company",
            ),
        ),
    ]
