# Generated by Django 6.0.3 on 2026-03-29 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_rename_ventas_cobros_to_crm_soporte"),
        ("users", "0004_add_tenant_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Formato: modulo.accion (ej: proyectos.edit)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("modulo", models.CharField(max_length=50)),
                ("accion", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "ordering": ["modulo", "accion"],
                "indexes": [
                    models.Index(
                        fields=["modulo", "accion"],
                        name="users_permi_modulo_cb6ccd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("readonly", "Solo Lectura"),
                            ("custom", "Personalizado"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="True para roles Admin y Solo Lectura — no se pueden eliminar",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="companies.company",
                    ),
                ),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="users.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="rol_granular",
            field=models.ForeignKey(
                blank=True,
                help_text="Rol granular con permisos específicos",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="users.role",
            ),
        ),
    ]
