# Generated by Django 6.0.3 on 2026-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_permission_role_granular"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(
                default=False, help_text="True para usuarios bot/IA"
            ),
        ),
    ]
