# Generated by Django 6.0.3 on 2026-04-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invited_at",
            field=models.DateTimeField(
                blank=True, help_text="Fecha en que se envió la invitación", null=True
            ),
        ),
    ]
