# Generated by Django 5.0.6 on 2026-03-19 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_company_plan_saiopen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionConsecutivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entidad",
                    models.CharField(
                        choices=[
                            ("proyecto", "Proyecto"),
                            ("actividad", "Actividad"),
                            ("factura", "Factura"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subtipo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtipo (ej: tipo de proyecto o tipo de actividad). Vacío = sin subtipo.",
                        max_length=50,
                    ),
                ),
                (
                    "prefijo",
                    models.CharField(
                        help_text="Ej: PRY, OBR, MTO, ACT, MAT", max_length=20
                    ),
                ),
                ("ultimo_numero", models.PositiveIntegerField(default=0)),
                (
                    "formato",
                    models.CharField(
                        default="{prefijo}-{numero:04d}",
                        help_text="Template Python. Variables: {prefijo}, {numero}. Ej: {prefijo}-{numero:04d}",
                        max_length=100,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de consecutivo",
                "verbose_name_plural": "Configuraciones de consecutivos",
                "ordering": ["entidad", "subtipo"],
                "unique_together": {("company", "entidad", "subtipo")},
            },
        ),
    ]
