# Generated by Django 5.0.6 on 2026-03-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_consecutivo_add_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionconsecutivo",
            name="formato",
            field=models.CharField(
                default="{prefijo}-{numero:04d}",
                help_text="Template Python. Variables: {prefijo}, {numero}.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionconsecutivo",
            name="nombre",
            field=models.CharField(
                help_text="Nombre descriptivo. Ej: Proyectos obra civil, Actividades material",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionconsecutivo",
            name="prefijo",
            field=models.CharField(
                help_text="Único por empresa. Ej: OBR, MOB", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="configuracionconsecutivo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("proyecto", "Proyecto"),
                    ("actividad", "Actividad"),
                    ("factura", "Factura"),
                    ("tercero", "Tercero"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionconsecutivo",
            name="ultimo_numero",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número desde el cual se generará el siguiente código. Útil para continuar una secuencia existente.",
            ),
        ),
    ]
