# Generated by Django 6.0.3 on 2026-04-07 19:49

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0005_conversacion_bot_context"),
        ("companies", "0010_add_agent_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("drive", "Google Drive"),
                            ("upload", "Panel Admin"),
                            ("cli", "Management Command"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "original_format",
                    models.CharField(
                        help_text="Extensión del archivo original: md, pdf, docx, txt",
                        max_length=10,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Módulo al que pertenece: proyectos, dashboard, terceros, contabilidad, general",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("norma", "Norma"),
                            ("faq", "FAQ"),
                            ("guia", "Guía"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 del contenido para detectar cambios y evitar re-procesar",
                        max_length=64,
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("last_indexed_at", models.DateTimeField()),
                (
                    "drive_file_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Drive file ID (solo canal drive)",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "ordering": ["-last_indexed_at"],
                "unique_together": {("company", "file_name", "source_channel")},
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.SmallIntegerField(
                        help_text="1 = thumbs up, -1 = thumbs down"
                    ),
                ),
                (
                    "module_context",
                    models.CharField(
                        help_text="Módulo donde se dio el feedback", max_length=50
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="Pregunta original del usuario"),
                ),
                (
                    "answer",
                    models.TextField(help_text="Respuesta del bot que se evaluó"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "mensaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedbacks",
                        to="chat.mensaje",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Feedback",
                "verbose_name_plural": "AI Feedbacks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "mensaje")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual de usuario"),
                            ("norma", "Norma colombiana"),
                            ("faq_aprendida", "FAQ aprendida"),
                            ("help_text", "Help text"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="Ruta o nombre del archivo fuente. Ej: docs/manuales/MANUAL-PROYECTOS.md",
                        max_length=255,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Módulo: proyectos, dashboard, terceros, contabilidad, general",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536,
                        help_text="Embedding vectorial (text-embedding-3-small, 1536 dims)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata adicional: section, subsection, page, etc.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fuente del chunk. Null para FAQ aprendidas sin archivo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai.knowledgesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Chunk",
                "verbose_name_plural": "Knowledge Chunks",
                "ordering": ["-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="kb_embedding_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
