# Generated by Django 5.0.6 on 2026-03-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terceros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tercero",
            name="tipo_tercero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cliente", "Cliente"),
                    ("proveedor", "Proveedor"),
                    ("subcontratista", "Subcontratista"),
                    ("interventor", "Interventor"),
                    ("consultor", "Consultor"),
                    ("empleado", "Empleado"),
                    ("otro", "Otro"),
                ],
                help_text="Clasificación principal. Un tercero puede tener varios roles via TerceroProyecto.",
                max_length=20,
            ),
        ),
    ]
