# Generated by Django 5.0.6 on 2026-03-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymodule",
            name="module",
            field=models.CharField(
                choices=[
                    ("ventas", "SaiVentas"),
                    ("cobros", "SaiCobros"),
                    ("dashboard", "SaiDashboard"),
                    ("proyectos", "SaiProyectos"),
                ],
                max_length=20,
            ),
        ),
    ]
