# Generated by Django 6.0.3 on 2026-03-29 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companylicense_licensepayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companylicense",
            name="ai_tokens_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="Tokens IA disponibles por mes"
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="ai_tokens_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Tokens IA usados en el período actual"
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="concurrent_users",
            field=models.PositiveIntegerField(
                default=1, help_text="Número máximo de usuarios simultáneos permitidos"
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Superadmin que creó esta licencia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="last_reset_date",
            field=models.DateField(
                blank=True,
                help_text="Última vez que se resetearon los contadores mensuales",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="messages_quota",
            field=models.PositiveIntegerField(
                default=0, help_text="Mensajes IA disponibles por mes"
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="messages_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Mensajes IA usados en el período actual"
            ),
        ),
        migrations.AddField(
            model_name="companylicense",
            name="modules_included",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de slugs de módulos incluidos. Ej: ["proyectos", "ventas"]',
            ),
        ),
        migrations.CreateModel(
            name="LicenseHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Creada"),
                            ("renewed", "Renovada"),
                            ("extended", "Extendida"),
                            ("suspended", "Suspendida"),
                            ("activated", "Activada"),
                            ("modified", "Modificada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="companies.companylicense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de licencia",
                "verbose_name_plural": "Historial de licencias",
                "ordering": ["-created_at"],
            },
        ),
    ]
