# Generated by Django 6.0.3 on 2026-03-29 19:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_license_concurrent_modules_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companylicense",
            name="period",
            field=models.CharField(
                choices=[
                    ("trial", "Prueba (14 días)"),
                    ("monthly", "Mensual (30 días)"),
                    ("bimonthly", "Bimestral (60 días)"),
                    ("quarterly", "Trimestral (90 días)"),
                    ("annual", "Anual (360 días)"),
                ],
                default="trial",
                help_text="Período de la licencia.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("created", "Creada"),
                    ("renewed", "Renovada"),
                    ("extended", "Extendida"),
                    ("suspended", "Suspendida"),
                    ("activated", "Activada"),
                    ("modified", "Modificada"),
                    ("renewal_generated", "Renovación generada"),
                    ("renewal_confirmed", "Pago confirmado"),
                    ("renewal_activated", "Renovación activada"),
                    ("renewal_cancelled", "Renovación cancelada"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LicenseRenewal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("trial", "Prueba (14 días)"),
                            ("monthly", "Mensual (30 días)"),
                            ("bimonthly", "Bimestral (60 días)"),
                            ("quarterly", "Trimestral (90 días)"),
                            ("annual", "Anual (360 días)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("new_starts_at", models.DateField()),
                ("new_expires_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de pago"),
                            ("confirmed", "Pago confirmado"),
                            ("activated", "Activada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("manual", "Manual"), ("gateway", "Pasarela de pago")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("gateway_payload", models.JSONField(blank=True, default=dict)),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Generada automáticamente por el sistema",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewals_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="companies.companylicense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renovación de licencia",
                "verbose_name_plural": "Renovaciones de licencia",
                "ordering": ["-created_at"],
            },
        ),
    ]
