# Generated by Django 6.0.3 on 2026-03-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_add_period_license_renewal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companylicense",
            name="modules_included",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de slugs de módulos incluidos. Ej: ["proyectos", "crm"]',
            ),
        ),
        migrations.AlterField(
            model_name="companymodule",
            name="module",
            field=models.CharField(
                choices=[
                    ("crm", "CRM"),
                    ("soporte", "Soporte"),
                    ("dashboard", "SaiDashboard"),
                    ("proyectos", "SaiProyectos"),
                ],
                max_length=20,
            ),
        ),
    ]
