# Generated by Django 6.0.3 on 2026-04-04 03:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicensePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Slug unico: mod_dashboard, seats_5, ai_1000",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("module", "Modulo"),
                            ("user_seats", "Puestos de usuario"),
                            ("ai_tokens", "Tokens IA"),
                            ("ai_messages", "Mensajes IA"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Solo para type=module. Ej: dashboard, proyectos",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Cantidad: seats o tokens segun tipo"
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio mensual COP",
                        max_digits=15,
                    ),
                ),
                (
                    "price_annual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio anual COP",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paquete de licencia",
                "verbose_name_plural": "Paquetes de licencia",
                "ordering": ["package_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        help_text="Tipo: cfo_virtual, project_assistant, manual_guide",
                        max_length=50,
                    ),
                ),
                (
                    "module_context",
                    models.CharField(
                        help_text="Modulo: dashboard, proyectos, general", max_length=50
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=50)),
                (
                    "question_preview",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primeros 200 chars de la pregunta",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de uso IA",
                "verbose_name_plural": "Registros de uso IA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="companies_a_company_7be4ef_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="companies_a_user_id_0f5136_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LicensePackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Cantidad de este paquete asignado"
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="companies.companylicense",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="companies.licensepackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete asignado",
                "verbose_name_plural": "Paquetes asignados",
                "ordering": ["-added_at"],
                "unique_together": {("license", "package")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyLicenseSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Primer dia del mes del snapshot"),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Estado completo de la licencia al momento del snapshot",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="companies.companylicense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot mensual de licencia",
                "verbose_name_plural": "Snapshots mensuales de licencia",
                "ordering": ["-month"],
                "unique_together": {("license", "month")},
            },
        ),
    ]
