# Generated by Django 6.0.3 on 2026-04-04 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_licensepackage_aiusagelog_licensepackageitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Etiqueta para identificar el equipo, ej: "PC principal oficina"',
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tokens",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de agente",
                "verbose_name_plural": "Tokens de agente",
                "ordering": ["-created_at"],
            },
        ),
    ]
