# Generated by Django 6.0.3 on 2026-04-09 05:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_add_agent_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="companylicense",
            name="plan",
        ),
        migrations.AddField(
            model_name="companylicense",
            name="renewal_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("auto", "Automática")],
                default="manual",
                help_text="Manual: el admin confirma la renovación. Automática: N8N genera la solicitud 5 días antes.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ModuleTrial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        help_text="Código del módulo: dashboard, proyectos, crm, soporte",
                        max_length=50,
                    ),
                ),
                (
                    "iniciado_en",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expira_en", models.DateTimeField(help_text="iniciado_en + 14 días")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_module_trials",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trial de módulo",
                "verbose_name_plural": "Trials de módulo",
                "ordering": ["-iniciado_en"],
                "unique_together": {("company", "module_code")},
            },
        ),
    ]
