# Generated by Django 6.0.3 on 2026-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_seed_user_and_ai_packages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companylicense",
            name="messages_quota",
        ),
        migrations.AlterField(
            model_name="companylicense",
            name="messages_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Mensajes IA enviados en el período actual"
            ),
        ),
    ]
