# Generated by Django 6.0.3 on 2026-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_add_license_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttoken",
            name="sync_server_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL base del sync server del agente, ej: http://192.168.1.100:8766",
                max_length=200,
            ),
        ),
    ]
