# Generated by Django 6.0.3 on 2026-04-10 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0015_add_license_request"),
        ("terceros", "0002_alter_tercero_tipo_tercero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmEtapa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "probabilidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("es_ganado", models.BooleanField(default=False)),
                ("es_perdido", models.BooleanField(default=False)),
                ("color", models.CharField(default="#2196F3", max_length=7)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa CRM",
                "verbose_name_plural": "Etapas CRM",
                "ordering": ["pipeline", "orden"],
            },
        ),
        migrations.CreateModel(
            name="CrmImpuesto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "porcentaje",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("es_default", models.BooleanField(default=False)),
                ("sai_key", models.CharField(blank=True, max_length=20, null=True)),
                ("saiopen_synced", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto CRM",
                "verbose_name_plural": "Impuestos CRM",
                "ordering": ["nombre"],
                "unique_together": {("company", "sai_key")},
            },
        ),
        migrations.CreateModel(
            name="CrmLeadScoringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "campo",
                    models.CharField(
                        help_text="Ej: fuente, empresa, email, telefono", max_length=50
                    ),
                ),
                (
                    "operador",
                    models.CharField(
                        choices=[
                            ("eq", "Igual a"),
                            ("contains", "Contiene"),
                            ("gte", "Mayor o igual a"),
                            ("lte", "Menor o igual a"),
                            ("not_empty", "No está vacío"),
                            ("is_empty", "Está vacío"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        blank=True, help_text="Valor a comparar", max_length=200
                    ),
                ),
                (
                    "puntos",
                    models.SmallIntegerField(help_text="Positivo suma, negativo resta"),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de scoring",
                "verbose_name_plural": "Reglas de scoring",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="CrmOportunidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                (
                    "valor_esperado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "probabilidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("fecha_cierre_estimada", models.DateField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True)),
                ("ganada_en", models.DateTimeField(blank=True, null=True)),
                ("perdida_en", models.DateTimeField(blank=True, null=True)),
                ("motivo_perdida", models.CharField(blank=True, max_length=200)),
                (
                    "proxima_actividad_fecha",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("proxima_actividad_tipo", models.CharField(blank=True, max_length=20)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_oportunidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_oportunidades",
                        to="terceros.tercero",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oportunidades",
                        to="crm.crmetapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidad CRM",
                "verbose_name_plural": "Oportunidades CRM",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrmCotizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_interno", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("validez_dias", models.PositiveSmallIntegerField(default=30)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("vencida", "Vencida"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "descuento_adicional_p",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "descuento_adicional_val",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("condiciones", models.TextField(blank=True)),
                ("sai_numero", models.IntegerField(blank=True, null=True)),
                ("sai_tipo", models.CharField(blank=True, max_length=3, null=True)),
                ("sai_empresa", models.SmallIntegerField(blank=True, null=True)),
                ("sai_sucursal", models.SmallIntegerField(blank=True, null=True)),
                ("sai_key", models.CharField(blank=True, max_length=50, null=True)),
                ("saiopen_synced", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_cotizaciones",
                        to="terceros.tercero",
                    ),
                ),
                (
                    "oportunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="crm.crmoportunidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización CRM",
                "verbose_name_plural": "Cotizaciones CRM",
                "ordering": ["-created_at"],
                "unique_together": {("company", "sai_key")},
            },
        ),
        migrations.CreateModel(
            name="CrmActividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("llamada", "Llamada"),
                            ("reunion", "Reunión"),
                            ("email", "Email"),
                            ("tarea", "Tarea"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_programada", models.DateTimeField()),
                ("completada", models.BooleanField(default=False)),
                ("completada_en", models.DateTimeField(blank=True, null=True)),
                ("resultado", models.TextField(blank=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "oportunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="crm.crmoportunidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad CRM",
                "verbose_name_plural": "Actividades CRM",
                "ordering": ["fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="CrmPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("es_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline CRM",
                "verbose_name_plural": "Pipelines CRM",
                "ordering": ["-es_default", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="crmoportunidad",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oportunidades",
                to="crm.crmpipeline",
            ),
        ),
        migrations.CreateModel(
            name="CrmLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("csv", "Importación CSV/Excel"),
                            ("webhook", "Formulario web (webhook)"),
                            ("email", "Correo entrante"),
                            ("otro", "Otro"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("convertido", models.BooleanField(default=False)),
                ("convertido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "tercero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to="terceros.tercero",
                    ),
                ),
                (
                    "oportunidad",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_origen_rel",
                        to="crm.crmoportunidad",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="crm.crmpipeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead CRM",
                "verbose_name_plural": "Leads CRM",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="crmetapa",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapas",
                to="crm.crmpipeline",
            ),
        ),
        migrations.CreateModel(
            name="CrmProducto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(db_index=True, max_length=30)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("unidad_venta", models.CharField(blank=True, max_length=20)),
                ("clase", models.CharField(blank=True, max_length=10)),
                ("grupo", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sai_key", models.CharField(blank=True, max_length=30, null=True)),
                ("saiopen_synced", models.BooleanField(default=False)),
                ("ultima_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.crmimpuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto CRM",
                "verbose_name_plural": "Productos CRM",
                "ordering": ["nombre"],
                "unique_together": {("company", "sai_key")},
            },
        ),
        migrations.CreateModel(
            name="CrmTimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nota", "Nota"),
                            ("cambio_etapa", "Cambio de etapa"),
                            ("actividad_completada", "Actividad completada"),
                            ("email_enviado", "Email enviado"),
                            ("cotizacion_creada", "Cotización creada"),
                            ("cotizacion_aceptada", "Cotización aceptada"),
                            ("lead_convertido", "Lead convertido"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "oportunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="crm.crmoportunidad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento timeline CRM",
                "verbose_name_plural": "Eventos timeline CRM",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="crmetapa",
            unique_together={("pipeline", "orden")},
        ),
        migrations.CreateModel(
            name="CrmLineaCotizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conteo", models.PositiveSmallIntegerField()),
                ("descripcion", models.CharField(max_length=200)),
                ("descripcion_adic", models.TextField(blank=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=4, default=1, max_digits=15),
                ),
                (
                    "vlr_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "descuento_p",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "iva_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_parcial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("proyecto", models.CharField(blank=True, max_length=10)),
                ("actividad", models.CharField(blank=True, max_length=3)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="crm.crmcotizacion",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.crmimpuesto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.crmproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de cotización",
                "verbose_name_plural": "Líneas de cotización",
                "ordering": ["conteo"],
                "unique_together": {("cotizacion", "conteo")},
            },
        ),
    ]
