# Generated by Django 6.0.3 on 2026-04-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmactividad",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="crm.crmlead",
            ),
        ),
        migrations.AlterField(
            model_name="crmactividad",
            name="oportunidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="crm.crmoportunidad",
            ),
        ),
    ]
