# Generated by Django 6.0.3 on 2026-03-30 15:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0007_rename_ventas_cobros_to_crm_soporte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ultimo_mensaje_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "participante_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participante_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación",
                "verbose_name_plural": "Conversaciones",
                "ordering": ["-ultimo_mensaje_at"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contenido", models.TextField(blank=True)),
                ("contenido_html", models.TextField(blank=True)),
                (
                    "imagen_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("leido_por_destinatario", models.BooleanField(default=False)),
                ("leido_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="chat.conversacion",
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responde_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respuestas",
                        to="chat.mensaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversacion",
            name="ultimo_mensaje",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.mensaje",
            ),
        ),
        migrations.AddIndex(
            model_name="mensaje",
            index=models.Index(
                fields=["conversacion", "created_at"],
                name="chat_mensaj_convers_dfb3a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(
                fields=["company", "-ultimo_mensaje_at"],
                name="chat_conver_company_25a652_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversacion",
            unique_together={("company", "participante_1", "participante_2")},
        ),
    ]
