# Generated by Django 6.0.3 on 2026-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="archivo_nombre",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="archivo_tamaño",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="archivo_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
