# Generated by Django 6.0.3 on 2026-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_archivo_fields_to_mensaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="thumbnail_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
