# Generated by Django 6.0.3 on 2026-03-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_add_thumbnail_url_to_mensaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="contenido_original",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="editado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="editado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
