# Generated by Django 6.0.3 on 2026-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_edicion_fields_to_mensaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversacion",
            name="bot_context",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contexto del modulo para conversaciones con bot: dashboard, proyectos, general",
                max_length=50,
            ),
        ),
    ]
